version: '3.8'

services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=atm-service-db
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=cppenloglou
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$password"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

