apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose-remote.yaml -o kubernetes/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: atm-service-frontend
  name: atm-service-frontend
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    io.kompose.service: atm-service-frontend
