apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose-remote.yaml -o kubernetes/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: atm-service-microservice
  name: atm-service-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: atm-service-microservice
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose-remote.yaml -o kubernetes/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: atm-service-microservice
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/atm-service-db
            - name: SPRING_DATASOURCE_USERNAME
              value: cppenloglou
          image: cppenloglou/atm-service-api:1.0
          imagePullPolicy: Always
          name: atm-service-api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
